#! /bin/sh -

CUR=`pwd`
DIR=`basename "${CUR}"`

if [ z"$1" = z"-n" ] ; then
  FILT="-newer ${DIR}/`ls -t y-ignore-me/z-keep-backups/z*.tgz | grep -v bis.tgz | head -1`"
else
  FILT=""
fi

cd ..
find "${DIR}" -type f ${FILT} | grep -v '/build/' | grep -v .jar | sort
