#! /bin/sh -

usage() {
  echo Usage: $0 exec.jar file.xcd >&2
  exit 1
}

if [ $# != 2 ]; then
  echo Need exactly two arguments 2>&1
  usage
fi

TARGETJAR=$1
shift 1

TSTDIR=`dirname $1`
TST=`basename $1 .xcd`

CURRDIR=`pwd`
TESTDIROUT="${CURRDIR}/build/test"
case "z${TSTDIR}" in
 z/*)
        TESTDIRIN="${TSTDIR}"
        ;;
 *)
        TESTDIRIN="${CURRDIR}/${TSTDIR}"
        ;;
esac
case "z${TARGETJAR}" in
 z/*)
        ;;
 *)
        TARGETJAR="${CURRDIR}/${TARGETJAR}"
        ;;
esac
INPUT="${TESTDIRIN}/${TST}.xcd"
OUTPUTOK="${TESTDIROUT}/${TST}.passed"
OUTPUTKO="${TESTDIROUT}/${TST}.failed"

if [ "z${TST}z" = zz -o ! -f "${INPUT}" -o ! -f "${TARGETJAR}" ]; then
  if [ "z${TST}z" = zz -o ! -f "${INPUT}" ]; then
    echo Cannot find model file "${INPUT}" 2>&1
  fi
  if [ ! -f "${TARGETJAR}" ]; then
    echo Cannot find jar file "${TARGETJAR}" 2>&1
  fi
  # echo Usage: $0 exec.jar file.xcd >&2
  # exit 1
  usage
fi

# rm -f build/test/${TST}.passed > /dev/null 2>&1

mkdir -p "${TESTDIROUT}/${TST}" 

( cd "${TESTDIROUT}/${TST}" \
; java -jar "${TARGETJAR}" < "${INPUT}" ) \
> "${OUTPUTOK}" 2>&1

RES=$?
ERR=`head -1 "${OUTPUTOK}" | egrep '^line [0-9]'`

if [ ${RES} = 0 -a "z${ERR}z" = zz ]; then
  echo '        OK'
  exit 0
else
  mv "${OUTPUTOK}" "${OUTPUTKO}"
  echo '  KO'
  exit 1
fi
